/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLClassmngClassScheduleItem.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API
// Classes:
//   GTLClassmngClassScheduleItem (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLClassmngClassScheduleItem
//

@interface GTLClassmngClassScheduleItem : GTLObject
@property (nonatomic, retain) NSNumber *courseId;  // longLongValue
@property (nonatomic, copy) NSString *courseName;
@property (nonatomic, copy) NSString *endTime;
@property (nonatomic, copy) NSString *professor;
@property (nonatomic, copy) NSString *semesterEnd;
@property (nonatomic, copy) NSString *semesterStart;
@property (nonatomic, copy) NSString *startTime;
@property (nonatomic, retain) NSNumber *weekday;  // longLongValue
@end
