/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLClassmngClassScheduleItem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API
// Classes:
//   GTLClassmngClassScheduleItem (0 custom class methods, 8 custom properties)

#import "GTLClassmngClassScheduleItem.h"

// ----------------------------------------------------------------------------
//
//   GTLClassmngClassScheduleItem
//

@implementation GTLClassmngClassScheduleItem
@dynamic courseId, courseName, endTime, professor, semesterEnd, semesterStart,
         startTime, weekday;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"semesterEnd" : @"semester_end",
    @"semesterStart" : @"semester_start"
  };
  return map;
}

@end
