/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLClassmngUserMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API
// Classes:
//   GTLClassmngUserMessage (0 custom class methods, 4 custom properties)

#import "GTLClassmngUserMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLClassmngUserMessage
//

@implementation GTLClassmngUserMessage
@dynamic authDomain, email, federatedIdentity, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"authDomain" : @"auth_domain",
    @"federatedIdentity" : @"federated_identity",
    @"userId" : @"user_id"
  };
  return map;
}

@end
