/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLClassmng.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API

#import "GTLClassmngConstants.h"

#import "GTLClassmngClassScheduleItem.h"
#import "GTLClassmngUserClassSchedule.h"
#import "GTLClassmngUserMessage.h"

#import "GTLQueryClassmng.h"
#import "GTLServiceClassmng.h"
