/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLClassmngConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API

#import "GTLClassmngConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeClassmngUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
