/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLClassmngUserClassSchedule.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API
// Classes:
//   GTLClassmngUserClassSchedule (0 custom class methods, 2 custom properties)

#import "GTLClassmngUserClassSchedule.h"

#import "GTLClassmngClassScheduleItem.h"
#import "GTLClassmngUserMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLClassmngUserClassSchedule
//

@implementation GTLClassmngUserClassSchedule
@dynamic registeredCourses, user;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"registeredCourses" : @"registered_courses"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"registered_courses" : [GTLClassmngClassScheduleItem class]
  };
  return map;
}

@end
