/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryClassmng.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryClassmng (3 custom class methods, 3 custom properties)
//   GTLClassmngClassmngDownloadRegisteredCourses (0 custom class methods, 8 custom properties)
//   GTLClassmngClassmngDownloadUser (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLClassmngClassmngDownloadRegisteredCourses;
@class GTLClassmngClassmngDownloadUser;
@class GTLClassmngUserClassSchedule;

@interface GTLQueryClassmng : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, retain) GTLClassmngClassmngDownloadRegisteredCourses *registeredCourses;
@property (nonatomic, retain) GTLClassmngClassmngDownloadUser *user;

#pragma mark - "classmng" methods
// These create a GTLQueryClassmng object.

// Method: classmng.classmng.add
//  Authorization scope(s):
//   kGTLAuthScopeClassmngUserinfoEmail
// Fetches a GTLClassmngUserClassSchedule.
+ (instancetype)queryForClassmngAddWithObject:(GTLClassmngUserClassSchedule *)object;

// Method: classmng.classmng.download
//  Optional:
//   registeredCourses: GTLClassmngClassmngDownloadRegisteredCourses
//   user: GTLClassmngClassmngDownloadUser
//  Authorization scope(s):
//   kGTLAuthScopeClassmngUserinfoEmail
// Fetches a GTLClassmngUserClassSchedule.
+ (instancetype)queryForClassmngDownload;

// Method: classmng.classmng.drop
//  Authorization scope(s):
//   kGTLAuthScopeClassmngUserinfoEmail
// Fetches a GTLClassmngUserClassSchedule.
+ (instancetype)queryForClassmngDropWithObject:(GTLClassmngUserClassSchedule *)object;

@end

#pragma mark - method parameter objects
// These object are used only to pass a collection of parameters to a
// method as a single item.

// ----------------------------------------------------------------------------
//
//   GTLClassmngClassmngDownloadRegisteredCourses
//

// Used for 'registeredCourses' parameter on 'classmng.classmng.download'.

@interface GTLClassmngClassmngDownloadRegisteredCourses : GTLObject
@property (nonatomic, retain) NSNumber *courseId;  // longLongValue
@property (nonatomic, copy) NSString *courseName;
@property (nonatomic, copy) NSString *endTime;
@property (nonatomic, copy) NSString *professor;
@property (nonatomic, copy) NSString *semesterEnd;
@property (nonatomic, copy) NSString *semesterStart;
@property (nonatomic, copy) NSString *startTime;
@property (nonatomic, retain) NSNumber *weekday;  // longLongValue
@end

// ----------------------------------------------------------------------------
//
//   GTLClassmngClassmngDownloadUser
//

// Used for 'user' parameter on 'classmng.classmng.download'.

@interface GTLClassmngClassmngDownloadUser : GTLObject
@property (nonatomic, copy) NSString *authDomain;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *federatedIdentity;
@property (nonatomic, copy) NSString *userId;
@end
