/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySchedule.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySchedule (2 custom class methods, 4 custom properties)
//   GTLScheduleScheduleDownloadScheduledEvents (0 custom class methods, 5 custom properties)
//   GTLScheduleScheduleDownloadUser (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLScheduleScheduleDownloadScheduledEvents;
@class GTLScheduleScheduleDownloadUser;
@class GTLScheduleUserScheduledEvents;

@interface GTLQuerySchedule : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, retain) GTLScheduleScheduleDownloadScheduledEvents *scheduledEvents;
@property (nonatomic, copy) NSString *updateTime;
@property (nonatomic, retain) GTLScheduleScheduleDownloadUser *user;

#pragma mark - "schedule" methods
// These create a GTLQuerySchedule object.

// Method: schedule.schedule.download
//  Optional:
//   scheduledEvents: GTLScheduleScheduleDownloadScheduledEvents
//   updateTime: NSString
//   user: GTLScheduleScheduleDownloadUser
//  Authorization scope(s):
//   kGTLAuthScopeScheduleUserinfoEmail
// Fetches a GTLScheduleUserScheduledEvents.
+ (instancetype)queryForScheduleDownload;

// Method: schedule.schedule.upload
// if my_model.from_datastore: raise endpoints.BadRequestException( 'MyModel %s
// with parent %s already exists.' % (my_model.id, my_model.username))
//  Authorization scope(s):
//   kGTLAuthScopeScheduleUserinfoEmail
// Fetches a GTLScheduleUserScheduledEvents.
+ (instancetype)queryForScheduleUploadWithObject:(GTLScheduleUserScheduledEvents *)object;

@end

#pragma mark - method parameter objects
// These object are used only to pass a collection of parameters to a
// method as a single item.

// ----------------------------------------------------------------------------
//
//   GTLScheduleScheduleDownloadScheduledEvents
//

// Used for 'scheduledEvents' parameter on 'schedule.schedule.download'.

@interface GTLScheduleScheduleDownloadScheduledEvents : GTLObject
@property (nonatomic, copy) NSString *endTime;
@property (nonatomic, copy) NSString *eventDate;
@property (nonatomic, retain) NSNumber *eventId;  // longLongValue
@property (nonatomic, copy) NSString *eventName;
@property (nonatomic, copy) NSString *startTime;
@end

// ----------------------------------------------------------------------------
//
//   GTLScheduleScheduleDownloadUser
//

// Used for 'user' parameter on 'schedule.schedule.download'.

@interface GTLScheduleScheduleDownloadUser : GTLObject
@property (nonatomic, copy) NSString *authDomain;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *federatedIdentity;
@property (nonatomic, copy) NSString *userId;
@end
