/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySchedule.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySchedule (2 custom class methods, 4 custom properties)
//   GTLScheduleScheduleDownloadScheduledEvents (0 custom class methods, 5 custom properties)
//   GTLScheduleScheduleDownloadUser (0 custom class methods, 4 custom properties)

#import "GTLQuerySchedule.h"

#import "GTLScheduleUserScheduledEvents.h"

@implementation GTLQuerySchedule

@dynamic fields, scheduledEvents, updateTime, user;

#pragma mark - "schedule" methods
// These create a GTLQuerySchedule object.

+ (instancetype)queryForScheduleDownload {
  NSString *methodName = @"schedule.schedule.download";
  GTLQuerySchedule *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLScheduleUserScheduledEvents class];
  return query;
}

+ (instancetype)queryForScheduleUploadWithObject:(GTLScheduleUserScheduledEvents *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"schedule.schedule.upload";
  GTLQuerySchedule *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLScheduleUserScheduledEvents class];
  return query;
}

@end

#pragma mark - method parameter objects
// These object are used only to pass a collection of parameters to a
// method as a single item.

// ----------------------------------------------------------------------------
//
//   GTLScheduleScheduleDownloadScheduledEvents
//

@implementation GTLScheduleScheduleDownloadScheduledEvents
@dynamic endTime, eventDate, eventId, eventName, startTime;
@end

// ----------------------------------------------------------------------------
//
//   GTLScheduleScheduleDownloadUser
//

@implementation GTLScheduleScheduleDownloadUser
@dynamic authDomain, email, federatedIdentity, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"authDomain" : @"auth_domain",
    @"federatedIdentity" : @"federated_identity",
    @"userId" : @"user_id"
  };
  return map;
}

@end
