/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryClassmng.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   classmng/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryClassmng (3 custom class methods, 3 custom properties)
//   GTLClassmngClassmngDownloadRegisteredCourses (0 custom class methods, 8 custom properties)
//   GTLClassmngClassmngDownloadUser (0 custom class methods, 4 custom properties)

#import "GTLQueryClassmng.h"

#import "GTLClassmngUserClassSchedule.h"

@implementation GTLQueryClassmng

@dynamic fields, registeredCourses, user;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map = @{
    @"registeredCourses" : @"registered_courses"
  };
  return map;
}

#pragma mark - "classmng" methods
// These create a GTLQueryClassmng object.

+ (instancetype)queryForClassmngAddWithObject:(GTLClassmngUserClassSchedule *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"classmng.classmng.add";
  GTLQueryClassmng *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLClassmngUserClassSchedule class];
  return query;
}

+ (instancetype)queryForClassmngDownload {
  NSString *methodName = @"classmng.classmng.download";
  GTLQueryClassmng *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLClassmngUserClassSchedule class];
  return query;
}

+ (instancetype)queryForClassmngDropWithObject:(GTLClassmngUserClassSchedule *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"classmng.classmng.drop";
  GTLQueryClassmng *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLClassmngUserClassSchedule class];
  return query;
}

@end

#pragma mark - method parameter objects
// These object are used only to pass a collection of parameters to a
// method as a single item.

// ----------------------------------------------------------------------------
//
//   GTLClassmngClassmngDownloadRegisteredCourses
//

@implementation GTLClassmngClassmngDownloadRegisteredCourses
@dynamic courseId, courseName, endTime, professor, semesterEnd, semesterStart,
         startTime, weekday;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"semesterEnd" : @"semester_end",
    @"semesterStart" : @"semester_start"
  };
  return map;
}

@end

// ----------------------------------------------------------------------------
//
//   GTLClassmngClassmngDownloadUser
//

@implementation GTLClassmngClassmngDownloadUser
@dynamic authDomain, email, federatedIdentity, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"authDomain" : @"auth_domain",
    @"federatedIdentity" : @"federated_identity",
    @"userId" : @"user_id"
  };
  return map;
}

@end
