/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLScheduleUserScheduledEvents.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API
// Classes:
//   GTLScheduleUserScheduledEvents (0 custom class methods, 3 custom properties)

#import "GTLScheduleUserScheduledEvents.h"

#import "GTLScheduleDEvent.h"
#import "GTLScheduleUserMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLScheduleUserScheduledEvents
//

@implementation GTLScheduleUserScheduledEvents
@dynamic scheduledEvents, updateTime, user;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"scheduledEvents" : [GTLScheduleDEvent class]
  };
  return map;
}

@end
