/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLScheduleUserScheduledEvents.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API
// Classes:
//   GTLScheduleUserScheduledEvents (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLScheduleDEvent;
@class GTLScheduleUserMessage;

// ----------------------------------------------------------------------------
//
//   GTLScheduleUserScheduledEvents
//

@interface GTLScheduleUserScheduledEvents : GTLObject
@property (nonatomic, retain) NSArray *scheduledEvents;  // of GTLScheduleDEvent
@property (nonatomic, copy) NSString *updateTime;

// ProtoRPC container for users.User objects. Attributes: email: String; The
// email of the user. auth_domain: String; The auth domain of the user. user_id:
// String; The user ID. federated_identity: String; The federated identity of
// the user.
@property (nonatomic, retain) GTLScheduleUserMessage *user;

@end
