/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLScheduleConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API

#import "GTLScheduleConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeScheduleUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
