/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLScheduleDEvent.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API
// Classes:
//   GTLScheduleDEvent (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLScheduleDEvent
//

@interface GTLScheduleDEvent : GTLObject
@property (nonatomic, copy) NSString *endTime;
@property (nonatomic, copy) NSString *eventDate;
@property (nonatomic, retain) NSNumber *eventId;  // longLongValue
@property (nonatomic, copy) NSString *eventName;
@property (nonatomic, copy) NSString *startTime;
@end
