/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSchedule.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API

#import "GTLScheduleConstants.h"

#import "GTLScheduleDEvent.h"
#import "GTLScheduleUserMessage.h"
#import "GTLScheduleUserScheduledEvents.h"

#import "GTLQuerySchedule.h"
#import "GTLServiceSchedule.h"
