/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLScheduleDEvent.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   schedule/v1
// Description:
//   This is an API
// Classes:
//   GTLScheduleDEvent (0 custom class methods, 5 custom properties)

#import "GTLScheduleDEvent.h"

// ----------------------------------------------------------------------------
//
//   GTLScheduleDEvent
//

@implementation GTLScheduleDEvent
@dynamic endTime, eventDate, eventId, eventName, startTime;
@end
